apiVersion: apps/v1
kind: Deployment
metadata:
  name: practicecheckconfig-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: PracticeCheckConfig
  template:
    metadata:
      labels:
        app: PracticeCheckConfig
    spec:
      containers:
      - name: clouddemo
        image: dockcr.azurecr.io/clouddemo:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: dsconfigsn

---
apiVersion: v1
kind: Service
metadata:
  name: practicecheckconfig
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: PracticeCheckConfig